### ISSUE TITLE
mold can't be built with itself on mingw

### ISSUE THREAD

**Issue by ognevny** [rui314/mold#1288] opened 2024-06-22 08:36 UTC
linking fails with `mold: fatal: unknown -m argument: i386pep`. full logs can be found in https://github.com/msys2/MINGW-packages/actions/runs/9624122356?pr=21225

**Comment by mmuetzel** [comment] 2024-06-22 08:44
Probably a duplicate of #190.

**Comment by rui314** [comment] 2024-06-22 08:49
That's right. mold cannot build Windows binaries.

**Closed** 2024-06-22 08:49 UTC
