### ISSUE TITLE
Mold 1.1 fails to build ClickHouse; error linking protobuf

### ISSUE THREAD

**Issue by bin** [rui314/mold#391] opened 2022-03-09 16:53 UTC
Fails with the following message:

```
mold: fatal: contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o: don't know how to handle this LTO object file because no -plugin option was given
```

**Comment by rui314** [comment] 2022-03-10 01:43
I think you are doing LTO build but forgot to add `-flto` to the final link line. You need that option not only for creating object files but also for creating the final executable.

**Comment by bin** [comment] 2022-03-10 03:57
This is from the cmake auto-generated build; it runs fine without mold but breaks with `mold -run`.

**Comment by rui314** [comment] 2022-03-10 04:23
Even if it works with other linkers, it's not technically correct to not to add `-flto` to the final link line. IIUC, both LLVM and GCC require users to add `-flto` on all compiler driver invocation. Can you update the CMakeList.txt so that the final linker invocation has the `-flto` option?

**Comment by rui314** [comment] 2022-04-03 06:12
Did adding `-flto` to the linker command line solved the issue?

**Comment by ishitatsuyuki** [comment] 2022-04-25 08:41
I just made a fresh clone of ClickHouse and I cannot reproduce this. The build command line is:

```
CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build -G Ninja -S . -DENABLE_TESTS=OFF -DENABLE_THINLTO=ON -DLINKER_NAME=ld.mold
ninja -C build contrib/protobuf-cmake/all # partial build, but should be enough
```

(Linking actually segfaulted with mold 1.2.0 shipped with Arch, but looks like that was already fixed on master)

Officially ClickHouse only seems to be using ThinLTO (and it requires turning off the tests), not fat LTO.

The only place `protobuf/compiler/main.cc.o` is used is for `protoc`, which means that the executable linker flags will apply. ClickHouse correctly sets it:

https://github.com/ClickHouse/ClickHouse/blob/7380a713335e849f92a941e3ec1a9f46961a1176/CMakeLists.txt#L428

The only way this might fail (apart from using unsupported CMake flag combinations) is to use their "shared library" version of build, which is for faster iterations. They currently don't specify the correct flags for shared library linking. Even then, it looks like CMake would add in the C/CXX language compiler flags when linking shared library, which means that it will work, accidentally or intentionally.

I expect that ClickHouse will probably build with mold out-of-the-box. For OP, I suggest that you provide detailed build flags, otherwise this issue is not very actionable.

**Comment by rui314** [comment] 2022-04-25 08:49
@ishitatsuyuki Thanks for testing! Given this report, I'll close this bug.

@bin If you can still reproduce the issue, feel free to reopen this bug.

**Closed by rui314** 2022-04-25 08:49 UTC

**Comment by zamazan4ik** [comment] 2023-06-27 12:15
@ishitatsuyuki @rui314 I can reproduce the issue on my local machine. With completely the same flags `cmake ../ClickHouse -DLINKER_NAME=ld.mold -DENABLE_THINLTO=ON -DENABLE_TESTS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja` on running `ninja -C build contrib/protobuf-cmake/all` I get the error:

```
mold: fatal: contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o: don't know how to handle this LTO object file because no -plugin option was given. Please make sure you added -flto not only for creating object files but also for creating the final executable.
```

The full linker command looks like this:
```
"/home/zamazan4ik/open_source/build_ch/ld.lld" --sysroot=/home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -export-dynamic --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o contrib/protobuf-cmake/protoc /home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/crt1.o /home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/crti.o /home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9 -L/home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/lib/../lib64 -L/home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64 -L/home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/lib -L/home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib -plugin-opt=-generate-arange-section -plugin-opt=mcpu=x86-64 -plugin-opt=O3 -plugin-opt=thinlto -plugin-opt=-x86-branches-within-32B-boundaries -no-pie --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o contrib/protobuf-cmake/lib_libprotoc.a contrib/protobuf-cmake/lib_libprotobuf.a -lpthread contrib/zlib-ng-cmake/lib_zlib.a base/glibc-compatibility/libglibc-compatibility.a base/glibc-compatibility/memcpy/libmemcpy.a base/glibc-compatibility/libglibc-compatibility.a base/glibc-compatibility/memcpy/libmemcpy.a --start-group contrib/libcxx-cmake/libcxx.a contrib/libcxxabi-cmake/libcxxabi.a contrib/libunwind-cmake/libunwind.a --end-group /usr/lib64/clang/16/lib/linux/libclang_rt.builtins-x86_64.a -lc -lm -lrt -lpthread -ldl /home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9/crtend.o /home/zamazan4ik/open_source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/crtn.o
```

`/home/zamazan4ik/open_source/build_ch/ld.lld` has the following text inside:
```
if [[ "$*" =~ -plugin-opt=thinlto ]]; then
    exec "/usr/bin/ld.mold" -plugin-opt=-generate-arange-section "$@"
else
    exec "/usr/bin/ld.mold" "$@"
fi
```

OS: Fedora 38
mold version: 1.11.0 (from Fedora repo) and built from the latest master branch (tested both - the same error)

**Comment by rui314** [comment] 2023-06-29 07:51
As the error message suggests, I'd first make sure that I have passed `-flto` option both when compiling object files and when creating a final executable. Are you sure you have passed `-flto` to the final linker invocation?

**Comment by ishitatsuyuki** [comment] 2023-06-29 08:16
LLD has hardcoded LLVM LTO built-in and makes it easy to ignore errors like this.
