### ISSUE TITLE
rust: unable to build openssl "vendored" 

### ISSUE THREAD

**Issue by appetrosyan** [rui314/mold#539] opened 2022-06-11 18:59 UTC
I'm trying to set up `mold` as the default linker for a project. The only problem so far is `openssl`. 

I need to statically link against OpenSSL, so I'm forwarding the `vendored` feature flag to the `openssl` crate, which runs a build script, which should build `OpenSSL` and link it. 

### Expected behaviour

Compiles without issue, e.g. the following command works: 
```
cargo build --release --features "vendored"
``` 

### Actual behaviour: 

Running 

```
mold --run cargo build --release --features "vendored" 
```

Fails with the following Error message

```
error: failed to run custom build command for `openssl-sys v0.9.74`

Caused by:
process didn't exit successfully: `/run/media/app/Work/Git/iroha/target/release/build/openssl-sys-28bc122341510e35/build-script-main` (exit status: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running "perl" "./Configure" "--prefix=/run/media/app/Work/Git/iroha/target/release/build/openssl-sys-dfef3daac6d3fbba/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
Configuring OpenSSL version 1.1.1o (0x101010ffL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

--- stderr
thread 'main' panicked at '


Error configuring OpenSSL build:
Command: "perl" "./Configure" "--prefix=/run/media/app/Work/Git/iroha/target/release/build/openssl-sys-dfef3daac6d3fbba/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
Exit status: exit status: 1


', /home/app/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.20.0+1.1.1o/src/lib.rs:490:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I'm not sure if I should be reporting it here, on the OpenSSL issue tracker or both.

**Comment by 64** [comment] 2022-06-12 19:10
Hmm, this error message is not too useful. Is there any way you can see what the configure command fails with exactly? Maybe you can modify the build script to print stdout or try to run the command manually.

**Comment by appetrosyan** [comment] 2022-06-13 07:01
Sadly this is the best that I can get out of it, (normally it only tells you that something failed). 

I've done some digging and I found a workaround, which hints at the solution. 

Running the compilation with `mold --run` always fails at this step, and doesn't fail if the `openssl` crate has already been linked (via `ld`). 

Running the compilation without `mold --run`, but instead by adding the target directives to `config.toml` succeeds both with the `unkown-linux-gnu` and `unknown-linux-musl` targets. Verified with `readelf`. 

As such, my suspicion is that `mold --run` overrides some environment variables that are used when running the build script for `openssl`. This can be verified by doing what `mold --run` does one by one, and seeing if any particular env-var causes a conflict. 

If that's the case, I'm not sure if this can be fixed on the OpenSSL side, or here.

**Comment by rui314** [comment] 2022-06-14 07:26
I just run the given command in `/tmp` and got the following error.

```
$ cargo build --release --features "vendored"
error: could not find `Cargo.toml` in `/tmp` or any parent directory
```

How can I reproduce your issue?

**Comment by ishitatsuyuki** [comment] 2022-06-14 11:54
Reproduced with 1.2.1, fixed with master. Please update.

**Comment by appetrosyan** [comment] 2022-06-14 12:11
So... how long until this hits the official repos of Arch?

**Comment by rui314** [comment] 2022-06-14 12:43
I'm thinking of making another release this month, as good bug fixes waiting for an official release have accumulated.

**Comment by rui314** [comment] 2022-06-17 00:46
I'll close this bug since it's already fixed in HEAD.

**Closed by rui314** 2022-06-17 00:46 UTC
