### ISSUE TITLE
add meson build system

### ISSUE THREAD

**Issue by vtorri** [rui314/mold#605] opened 2022-08-08 05:50 UTC
meson has several advantages:

 * very fast (a bit faster than cmake, especially on Windows platform)
 * nicer syntax than cmake (close to python)
 * options are clearly readable in a separate file
 * wrapdb features to manage dependencies

**Comment by eli-schwartz** [comment] 2022-08-08 06:05
Duplicate of #547

**Closed** 2022-08-08 06:19 UTC
