### ISSUE TITLE
Rust linking errors on armv7

### ISSUE THREAD

**Issue by turkerali** [rui314/mold#546] opened 2022-06-18 16:00 UTC
I am trying to build a small Rust project with mold, on an armv7 single board computer running ubuntu jammy with 5.18.1 kernel.
I set up mold as described in the readme. My rust version is 1.61.0 and my .cargo/config.toml has the following:

`[target.armv7-unknown-linux-gnueabihf]`
`linker = "clang"`
`rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]`

The build starts, and after 1-2 minutes I get hundreds of errors as below. Could you please help to debug this issue?

mold: error: /srv/emmc/aet_rust/project1/target/debug/deps/time_macros-b032d6f1a0bbceb0.time_macros.462d9d1f-cgu.0.rcgu.o:(.ARM.extab.text._ZN102_$LT$time_macros..format_description..modifier..Day$u20$as$u20$time_macros..to_tokens..ToTokenTree$GT$15into_token_tree17hb49b346cfbd3314aE): R_ARM_PREL31 relocation at offset 0x0 against symbol ``rust_eh_personality' can not be used; recompile with -fPIC
          
mold: error: /root/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libminiz_oxide-34a9fcb7eea014e2.rlib(miniz_oxide-34a9fcb7eea014e2.miniz_oxide.4c96bd19-cgu.0.rcgu.o):(.ARM.extab.text._ZN11miniz_oxide7deflate4core15CompressorOxide3new17h6535eda801d53a3aE): R_ARM_PREL31 relocation at offset 0x0 against symbol ``rust_eh_personality' can not be used; recompile with -fPIC

mold: error: /srv/emmc/aet_rust/project1/target/debug/deps/time_macros-b032d6f1a0bbceb0.time_macros.462d9d1f-cgu.5.rcgu.o:(.ARM.extab.text._ZN95_$LT$core..str..pattern..MultiCharEqPattern$LT$C$GT$$u20$as$u20$core..str..pattern..Pattern$GT$13into_searcher17h01acec8edafa5d9aE): R_ARM_PREL31 relocation at offset 0x0 against symbol ``rust_eh_personality' can not be used; recompile with -fPIC

mold: error: /srv/emmc/aet_rust/project1/target/debug/deps/time_macros-b032d6f1a0bbceb0.time_macros.462d9d1f-cgu.5.rcgu.o:(.ARM.extab.text._ZN95_$LT$core..str..pattern..MultiCharEqPattern$LT$C$GT$$u20$as$u20$core..str..pattern..Pattern$GT$13into_searcher17h04ba1117599d9617E): R_ARM_PREL31 relocation at offset 0x0 against symbol ``rust_eh_personality' can not be used; recompile with -fPIC

mold: error: /root/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libproc_macro-40f665737099dc39.rlib(proc_macro-40f665737099dc39.proc_macro.fa35fcce-cgu.0.rcgu.o):(.ARM.extab.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17h49f0d6e22512b689E): R_ARM_PREL31 relocation at offset 0x0 against symbol ``rust_eh_personality' can not be used; recompile with -fPIC

**Comment by rui314** [comment] 2022-06-19 03:33
This is a duplicate of https://github.com/rui314/mold/issues/545.

**Closed by rui314** 2022-06-19 03:33 UTC
Labels: duplicate
