### ISSUE TITLE
Linking rust crate `sqlx-macros` sometimes fails.

### ISSUE THREAD

**Issue by s0lst1ce** [rui314/mold#111] opened 2021-08-16 18:18 UTC
Hello! I built mold from the source on the master branch. I'm using it to for some rust projects of mine using `/path/to/mold -run cargo b` to compile my code. The latter depends on a crate (aka: library) called `sqlx-macros` which mold sometimes fails to link. Running it again has always ended up succeeding but I frequently get a `core dumb` nonetheless.

I'm running this under archlinux. Please tell me if I should provide more context. You can also find the source code that fails to compile at https://github.com/Botanism/rust-db-adapter/
*I know it says it's compiling `linker` but that's because the latter uses `db-adpater`, which is the crate the brings in `rust-macros` and thus sometimes fails to compile. I was able to reproduce the error with only `db-adapter`*

Here's the full output: 
```
note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.0.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.1.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.10.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.11.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.12.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.13.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.14.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.15.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.2.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.3.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.4.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.5.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.6.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.7.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.8.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.sqlx_macros.5vsi1twd-cgu.9.rcgu.o" "-o" "/path/to/source/code/rust/linker/target/debug/deps/libsqlx_macros-3876f9942c11cba9.so" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.5gtffcnwnkafp0k2.rcgu.o" "/path/to/source/code/rust/linker/target/debug/deps/sqlx_macros-3876f9942c11cba9.1xi21p8kk1w19rvo.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/path/to/source/code/rust/linker/target/debug/deps" "-L" "/path/to/source/code/rust/linker/target/debug/build/ring-2847ca9b3a08683d/out" "-L" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/path/to/source/code/rust/linker/target/debug/deps/libdotenv-5e37d55d61dec282.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libheck-cf6dd51f77ea7f1f.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libunicode_segmentation-ae6d550a78cebacb.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsyn-350afa968831a91c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsqlx_core-0c4bbc97a41cf621.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libhex-da5a3289133e0040.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libwhoami-e758a7e62be1eb12.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libdirs-a60958c244ffc7fd.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libdirs_sys-bdb5792767994b9a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtokio_stream-eca04f382a94e774.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libwebpki_roots-cafba540822e70ab.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsqlformat-226186195d9e566f.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libunicode_categories-73e28b350d3e6364.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libnom-60016c6e109c8e7a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/liblexical_core-999458f5d301296b.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libstatic_assertions-694a9e2183f79b8a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libarrayvec-d9fdc0ebc25cb311.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libbitvec-9ebb52408a4166d7.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfunty-3831bb750ea5c3cf.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libwyz-c1bddf723a5a8ba4.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtap-2ff71da465c3be0e.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libradium-e4804310bc1b3b66.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libregex-ee06c89f391a352e.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libaho_corasick-5705d81ec78b2985.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libregex_syntax-fd3b238c743d0ae9.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libthiserror-fbe0ec171b24797c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libcrc-917851b47de1953c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libbitflags-83efdadf8f2f408f.rlib" "/path/to/source/code/rust/linker/target/debug/deps/liburl-8a2e78e17c71d1e1.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libidna-e910cb3a72b6f114.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libform_urlencoded-93b4344785c671ce.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libmatches-e7406ff9578eacdd.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libpercent_encoding-b970f2d5524ede86.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libmd5-93d3cde2c8792e84.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libbyteorder-a97d9c1653f3ccb3.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsmallvec-07597d84eb6d38d4.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libatoi-b05036b8d82f32ff.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libnum_traits-6defae952a07200a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libstringprep-f4b7acc0c960a064.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libunicode_normalization-6990e56da1f308f3.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtinyvec-6c1d87ac64d0b512.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtinyvec_macros-185d853a862f14e5.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libunicode_bidi-fe5f5ab2dd6e9724.rlib" "/path/to/source/code/rust/linker/target/debug/deps/librand-c2326cc820e894cc.rlib" "/path/to/source/code/rust/linker/target/debug/deps/librand_chacha-c4b491b1bfa3026b.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libppv_lite86-9a1c37bf77d436b5.rlib" "/path/to/source/code/rust/linker/target/debug/deps/librand_core-12691441b574dd08.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libhmac-43493c5b3905f011.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libcrypto_mac-776c6b302dfbc645.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsubtle-cc3e2b17427401b8.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsha2-a5d81928e1a44c4c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libcpufeatures-96d325672869b836.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libopaque_debug-068dad749136bc76.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libdigest-47a05650435c7889.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libblock_buffer-221e21715f4dfeb4.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libgeneric_array-b7eebffe976f9fc4.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtypenum-a4e870cc65dab2fe.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libhashlink-552fd5e8ad22fbd6.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libserde_json-2ed7ea1b2b75bcd7.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libryu-3eb3e92ecfcc8c0d.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libitoa-1c45b19da4022ac8.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libindexmap-aaf5ea3a1cdcc3d6.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libhashbrown-14c4eb9ff28e0695.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libahash-e2b21934ab3b18ed.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libgetrandom-e65a9df879c85fca.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libcrossbeam_queue-93bf440bdf4f46aa.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libcrossbeam_utils-8654fc7d762355cd.rlib" "/path/to/source/code/rust/linker/target/debug/deps/liblazy_static-9702d1010b228fd0.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsqlx_rt-5e1fd18c8e3d052a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtokio_rustls-4464b5ae7911c484.rlib" "/path/to/source/code/rust/linker/target/debug/deps/librustls-8cfdc1f2c02aae9a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libbase64-1dc85ba4ab7f0d6c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsct-13218964152712a8.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libwebpki-3eb3b20e29355d52.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libring-e1c75d14e2d93c24.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libspin-27350e4678df10c9.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libuntrusted-c5b9911a4bdfcc93.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libtokio-8cb5ef3104f054e5.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libsignal_hook_registry-24979e7585598136.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libnum_cpus-9be2e3cc6e971f19.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libonce_cell-0a738e9c5eb1b83a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libbytes-f4ec7f2f74040ede.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libmio-f1b87033583cc0c0.rlib" "/path/to/source/code/rust/linker/target/debug/deps/liblibc-cff468349f6f16f3.rlib" "/path/to/source/code/rust/linker/target/debug/deps/liblog-c6d867ccc931c3c1.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libcfg_if-0a6225dcb261749c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libeither-1bb1271da429a7d4.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libserde-0cadeb66ce70bce1.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfutures_util-6f5d1e2a2610941c.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libmemchr-c6a87ef35200f4b5.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfutures_io-1b1e314a30bc23f6.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libslab-b9d11812a35fa10a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libpin_project_lite-6e8e8f6730f40e6a.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfutures_task-0050acc8b06f3e6f.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libpin_utils-0d27f5f7447e9d91.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfutures_channel-cf49d67d2bfba905.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfutures_sink-2ad0af3e81405101.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libfutures_core-68ebd664ef90b628.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libquote-406d83d36613c99e.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libproc_macro2-4be9975c291cb90b.rlib" "/path/to/source/code/rust/linker/target/debug/deps/libunicode_xid-27847ed32544c45e.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-780e38f4a1b7f1a0.rlib" "-Wl,--start-group" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-b6b48477bfa8c673.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-f560ec02638f7ffe.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-9c8eadb7013c9e0b.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-8b0ec8dbdb85d0bf.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-ba5d5ee707c805d2.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-55166126dbdd5e46.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c327b365eae3b2f3.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-416439b546a0d033.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-2581188d29552e15.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-da7b2635bfcce6ef.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-09200ed1945e7b2b.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-223ac369b29f5000.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-39562fe6600dd936.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-9b411bb7a19f81b3.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-64ea0581d80339f7.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-b2dbda88b377d685.rlib" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2a8415a96ed1d7dc.rlib" "-Wl,--end-group" "/home/s0lst1ce/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c4d9a5b072ee3191.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: mold: ./mold.h:2045: u64 align_to(u64, u64): Assertion `__builtin_popcount(align) == 1' failed.
          collect2: fatal error: ld terminated with signal 6 [Aborted], core dumped
          compilation terminated.
```

**Comment by rui314** [comment] 2021-08-19 02:55
I believe this is a subtle concurrency bug, but I can't reproduce the issue on my machine. Could you checkout `issue111` branch with `git checkout origin/issue111`, build it and try again? It should print out more information when an assertion is failed.

**Comment by s0lst1ce** [comment] 2021-08-19 10:58
I'm now using branch `issue111` and I will post the error once I get it again. Do note that it hasn't occurred again in the last two days I've been working with the project. I specifically ran it to find the error a few dozen times today, to no avail.

**Comment by rui314** [comment] 2021-08-19 12:01
Thanks. I believe I saw the same error before, and that was the motivation to make it print out the stack trace when an assertion fails, but I haven't seen the error these days too. I'm not sure if it's fixed or just hidden though.

**Comment by rui314** [comment] 2021-12-23 06:41
It doesn't seem to happen anymore, so I'll close this issue.

**Closed by rui314** 2021-12-23 06:41 UTC
