### ISSUE TITLE
Unknown command line option: -dynamic when using with latest clang release <14.0.5>

### ISSUE THREAD

**Issue by abpostelnicu** [rui314/mold#591] opened 2022-07-28 11:56 UTC
When running something similar to:

clang --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=11.0 -std=gnu99 --ld-path=/opt/homebrew/bin/mold -Wl,--version

The result is: mold: fatal: unknown command line option: -dynamic

Being more verbose the above command line translates to:
mold -dynamic -arch arm64 -macosx_version_min 11.0.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -o a.out --version -lSystem /Compilers/lib/clang/14.0.5/lib/darwin/libclang_rt.osx.a

**Comment by Alcaro** [comment] 2022-07-28 12:01
Duplicate of #551? Or is mold/macho ready to accept bug reports by now?

**Comment by rui314** [comment] 2022-07-28 12:09
It's duplicate of #551, and we are not yet accept bug reports for mold/macOS.

**Closed by rui314** 2022-07-28 12:09 UTC
